application:
  animal:
    possible-names: DogName, CatName, WolfName, SharkName

spring:
  liquibase:
    change-log: 'classpath:/db/changelog/db.changelog-master.yaml'
  datasource:
    username: postgres
    password: postgres
  jpa:
    open-in-view: false