spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mts_homework_sivelkaev_db?prepareThreshold=0
    username: sivelkaev
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

application:
  animal:
    possible-names: Barsik, Murzik, Sharik, SharkKiller